name: pious_squid
description: >-
  An astrodynamics library for the Dart ecosystem, covering orbital mechanics
  and satellite mission analysis logic.
version: 0.2.2
repository: https://github.com/david-rc-dayton/pious_squid

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
